# Generated by Django 5.2.6 on 2025-10-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('message_type', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('image', 'Image')])),
                ('sending_date', models.DateTimeField(auto_now=True)),
                ('receiving_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('send', 'Send'), ('received', 'Received'), ('read', 'Read')])),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('user_sen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.user')),
            ],
        ),
    ]
