# Generated by Django 5.2.6 on 2025-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_member',
            fields=[
                ('join_date', models.DateTimeField(auto_created=True)),
                ('member_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('group_id', models.IntegerField(unique=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')])),
            ],
        ),
    ]
